name: CI Pipeline check Math.ts

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Notify on Sucess
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
            -d '{"content":"✅ CI Passed on main branch!"}' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
      
      - name: Notify on Failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
            -d '{"content":"❌ CI Failed! Check the logs."}' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}