name: Database Migration Check

on:
  pull_request:
    paths:
      - 'migrations/**'
      - 'tests/migrations/**'
      - 'scripts/**'

jobs:
  migration-check:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for migration comparison

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create test database backup
      run: |
        python scripts/backup/create_backup.py
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db

    - name: Run migration tests
      run: |
        pytest tests/migrations/ -v
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db

    - name: Run performance tests
      run: |
        pytest tests/performance/ -v
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db

    - name: Generate performance report
      run: |
        python scripts/monitoring/generate_report.py
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db

    - name: Upload performance results
      uses: actions/upload-artifact@v3
      with:
        name: migration-performance-report
        path: |
          reports/performance.json
          backups/

    - name: Check migration reversibility
      run: |
        # Apply all migrations
        alembic upgrade head
        # Then roll them all back
        alembic downgrade base
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db 